### ISSUE TITLE
Can't get GPU on logan

### ISSUE THREAD

**Issue by rmattson1008** [rmattson1008/ornet#27]
I can get on but cannot use gpu. I get `No supported gpu backend found!` when I try to use. Could it be affected by UGA system maintenance? It looks like a lot of stuff is being worked on this week - [maintenance schedule](https://status.uga.edu/#/). I was having no trouble this morning.

**Comment by rmattson1008** [comment]
`nvidia-smi` asks me to install nvidia-smi, haha, `torch.cuda.is_available()` returns false

**Comment by magsol** [comment]
Entirely possible. I *just* got out of a meeting with Piotr in Franklin OIT, and he's still actively working on Logan because apparently there is some instability: occasionally Logan won't turn back on after a reboot, so he's looking into that. Precipitating the reboots are upgrades that may very well be the reason why you're getting that error message.

If you need a GPU, and if the process if feasible, we may want to temporarily relocate your work onto `rocinante` since there are plenty of GPUs available there @Micky774 .

**Comment by rmattson1008** [comment]
Ok, thanks for the quick response - I can work on other/adjacent stuff for a day or so. If Piotr indicates it might be a longer disruption then I can look at moving to rocinante.

**Comment by Micky774** [comment]
This should almost surely not fix it, but have you tried turning it off and back on again?

**Comment by rmattson1008** [comment]
I'm working out of one of the AI Institute Machines. Totally fine for now, but happy to move back to Logan when Piotr is done with it.

**Comment by magsol** [comment]
According to Piotr, he's updating Logan sometime this week. I'll keep you
apprised.
